### ISSUE TITLE
Add kerberos authentication support

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/bolt#106]
Please add kerberos auth support by adding the net-ssh-krb gem and allow `gssapi-with-mic` auth method.

https://github.com/cbeer/net-ssh-kerberos

You will probably need to add something like this to your connection options. 

https://github.com/nwops/kitchen-kerberos/blob/master/lib/train/transports/kerberos.rb#L74

**Comment by riton** [comment]
This request is related to [this jira issue](https://tickets.puppetlabs.com/browse/BOLT-168) and @joshcooper 's #107 .
We currently have released a [Puppet forge module](https://forge.puppet.com/ccin2p3/bolt) to address this very issue. But #107 should solve the issue. Partially anyway.

**Comment by joshcooper** [comment]
Even better solution is to support external `ssh` executables, filed as [BOLT-174](https://tickets.puppetlabs.com/browse/BOLT-174)

**Comment by joshcooper** [comment]
Support for the `gssapi-with-mic` authentication method was added in https://github.com/puppetlabs/bolt/commit/2ad71b7a9a59bdcb4562ce6ebea4f997949e5dc6 and will be released on 0.7.0 later this week. Due to GPLv2 licensing issues, bolt does not have a hard dependency on `net-ssh-krb` gem. However, if you manually install the gem (on the controller node), then bolt will make use of it. You may need to update/modify your `~/.ssh/config` to ensure the `gssapi-with-mic` authentication method is in your `PreferredAuthentications` option.
