### ISSUE TITLE
Is Analytics data collection really necessary?

### ISSUE THREAD

**Issue by pixdrift** [puppetlabs/bolt#1095]
Puppet / Bolt Developers,

I wanted to raise concerns that the Analytics Data Collection in Bolt seems unnecessary and is potentially impacting perception of the product.

Are we able to have a discussion about the data collection discussed in the documentation and if it is really necessary for development/improvement of the product? In any other context I think it could be described/interpreted as spyware.
https://puppet.com/docs/bolt/latest/bolt_installing.html#concept-8242

The idea that a customer/user has to '**opt out**' of the tool's analytics sending their every move back to Puppet breaks trust with the product (and Puppet) before the users even begin really using it. I also believe having this analytics module **on** by default shows a lack of respect for the customer/user.

For users that don't read the documentation in detail up front, I think seeing this level of telemetry being collected about their environment is going to raise alarm bells.

It would be great to see the default switched to disabled, or even a separate build of Bolt that has the telemetry elements completely removed (part of the reason for requesting SRPM here https://github.com/puppetlabs/bolt/issues/927).

**Comment by benridley** [comment]
Also curious about this. We're using Puppet in secure environments and this makes our security people nervous.

**Comment by yasminrajabi** [comment]
Hello!

My name's Yasmin and I'm the product manager for bolt. We use the analytics to track usage of the product in terms of how many installs we have and what functions are the most used. The data is completely anonymized and we don't track everything a user does, nor do we want to. We intentionally only track whether features are used, not *how* they are used so that we don't collect any information that could be sensitive. For example, we don't track the content that is used with bolt to avoid any sensitive information. 

This allows us to know if features are being used or not to help drive further investment or deprecation discussions. If you'd like to see the data bolt collects we've documented it [here](https://puppet.com/docs/bolt/latest/bolt_installing.html#concept-8242).  

For example, I look at a dashboard that shows us our total installs, how it trends over time, and whether more users using ssh or winrm? What type of operating systems are we installed on that we need to support? It helps us understand the usage that we wouldn't be able to collect in any other way. 

In addition, because we don't gate our installs with an email form, it can be difficult to understand usage at a broad level. Slack and github are great but only account for a small percentage of bolt users. We use this information to get investment from our leadership to continue to work on the project. Since it is open source, we need things like growth metrics to help us justify future improvements to the roadmap. 

That being said, anyone can [shut analytics off](https://puppet.com/docs/bolt/latest/bolt_installing.html#how-can-i-opt-out-of-bolt-data-collection). But you are right, it's not as easy as it could be. I've opened a ticket to discuss making it super clear at install time how to opt-out and including it in the install process. We'll discuss the approach in this [ticket](https://tickets.puppetlabs.com/browse/BOLT-1487) please leave feedback there if you're interested.

I'd love to understand a little more about your thoughts on the data collected. Is there a set of data that is tolerable? Would it be less of a concern if you can see the data? What if we make the data public? For us, it's not any secret information and could help the community as well. What are your thoughts on that?

**Comment by pixdrift** [comment]
Hi Yasmin,

Thanks for providing such a detailed response. For me, this doesn't really answer the question of if the analytics data collection _necessary_? I think it's telling in the wording in your final paragraph

> Is there a set of data that is tolerable?

Why tolerate this kind of behaviour from a product a user is downloading/evaluating by choice (and potentially consuming as a paying customer) when the prominent (and obvious alternative) competitor's product isn't encumbered in the same way? To me, this is like asking how many teaspoons of sand i'd be happy to tolerate in my morning coffee.. the answer will always be none.
<br />
  
> That being said, anyone can shut analytics off. But you are right, it's not as easy as it could be. I've opened a ticket to discuss making it super clear at install time how to opt-out and including it in the install process. We'll discuss the approach in this ticket please leave feedback there if you're interested.

My original post included the link of _what_ is collected by Bolt, I also linked to the documentation provided detailing how to turn it off. The original questions raised still remain though, why am I '**opting out**'? The fact that as a user/customer i'm required to **opt out** of the process makes the whole thing appear far more nefarious than it probably is. The proposal that i'd like Puppet to consider, is that if this 'feature' is to remain, that it at a minimum be switch to **opt-in**.
<br />

> In addition, because we don't gate our installs with an email form, it can be difficult to understand usage at a broad level. Slack and github are great but only account for a small percentage of bolt users. 

I would say the majority of open source projects don't gate their installs and instead build growth and success by producing compelling products and fostering community engagement. The core Puppet product is undeniable proof of this.

Puppet as a company have access to a vast collection of Bolt metrics other than just Slack and github that they could potentially fall back onto for mapping adoption, eg.

- Direct commercial engagement with Enterprise customers
- Contribution/pull metrics on Puppet forge, including module Bolt adoption
- Puppet's Internal customer ticketing system
- Bolt documentation page views/access/feedback
- 'State of DevOps' feedback survey, or customer email surveys
- Number of non-Puppet employee contributions to the Bolt github repository

With these resources available, is it really necessary for the metrics gathering to be stitched directly into the product to meet the internal leadership reporting requirement?
<br />

**Comment by yasminrajabi** [comment]
Hello,

I asked what data is tolerable to understand if its a set of data or all data, in addition to your question there was another user that asked about it so I was curious both points of view. It still remains something I'd like to understand from someone who has concerns about analytics if its a set of specific data or if its any data. But I definitely can see from your answer that for you it's all data.

To answer your question of if it's necessary, my answer would be yes. Like I mentioned, I along with many others in our company look at this data daily. It helps answers questions and we use it to justify investment, for example, was it a good idea to attend an event, run a free training, or have a virtual workshop? We are able to prove that by measuring total installs and correlate them by the time. Core puppet is gated today with an [email](https://puppet.com/download-open-source-puppet), that's not the approach we wanted to take with Bolt and instead left it open. 

The suggestions you gave for understanding adoption are great. They are touchpoints we use to measure the health of the project and find people to do follow up research with however, they are not accurate enough for how we are using the analytics today. I mentioned understanding total ssh vs. winrm usage, if we create a workshop for using powershell and winrm, is that something that was useful? Are we seeing more users using winrm as they use bolt? These are the types of things that we need the analytics to help answer, to continue adding value to the bolt project and ecosystem. At this point, we don't plan on changing the analytics to be opt-in, but again, we will make it easier and very clear to opt-out. This doesn't mean the discussion is ended for good, I think we can re-open it with some time, but given where the project is today and the additional investment required to help it grow, the analytics are helping us get that. If you'd like to discuss this further over a call or email I'm more than happy to continue, my email is yasmin @ puppet.

**Comment by pixdrift** [comment]
Thanks again for the response Yasmin, and for considering the proposal. 👍

**Comment by lucywyman** [comment]
We updated our install message to be more noticeable and clear on how to disable analytics. I'm going to close this issue - let us know if it needs to be reopened!
