### ISSUE TITLE
Using multiple modules directories

### ISSUE THREAD

**Issue by therek** [puppetlabs/bolt#112]
I keep modules in two different sub directories: `site` for mine code and `modules` for modules downloaded from Forge. As far as Puppet goes it can use both directories to look for modules. With Bolt, trying to pass them in `modulepath`-way (as `--modules ./site:./modules`) or with two parameters (`--modules ./site --modules ./modules`) ends in either my plan not being found, or dependencies not being met.

**Comment by joshcooper** [comment]
Hi [@therek], thanks for filing this. We're currently tracking this in https://tickets.puppetlabs.com/browse/BOLT-122 and somewhat related https://tickets.puppetlabs.com/browse/BOLT-121.

**Comment by cardil** [comment]
BTW. I think by default Bold should try to use `puppet config print modulemath` if path is not set explicite.

**Comment by hlindberg** [comment]
FWIW - the puppet PAL API (used by bolt) already supports being given a modulepath, and if given a configured puppet environment, will use the modulepath defined for that environment.

**Comment by joshcooper** [comment]
@therek The fix for multiple module directories was merged in https://github.com/puppetlabs/bolt/commit/c59edaa3eeca8348c0bdd1413c5e958ebde1a172. Note the option has changed to `modulepath` instead of `modules`, so I'm going to close this.

There is on-going discussion/work planned to default the `modulepath` option to whatever puppet is using. That work is being tracked in https://tickets.puppetlabs.com/browse/BOLT-121. Feel free to comment/watch that ticket.
