### ISSUE TITLE
It's hard to debug dynamic inventory.

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#1200]
## Use Case
It can be hard to debug dynamic inventory files. For example it's easy for a user to accidentally refer to dynamic information outside of a plugin block and other than writing a specific plan there is no way to see what is going on.

## Describe the Solution You Would Like
A command that resolves dynamic information in the inventory file and prints the results.
It probably should support both resolving the entire file or the data for a specific target. Should it show information only for a specific group or unmerged info for a target?

**Comment by lucywyman** [comment]
Use case 1: A target I'm trying to run on isn't using the config I expect. I want to see what config it's using.
Use case 2: I want to see the entire inventory resolved.
Use case 3: I also want to be able to know where a target got the config it's using.

**Comment by adreyer** [comment]
I think we should focus on usecase 1 for now. 

`bolt inventory show -n mynode --verbose` seems like a good starting syntax for that but there a few complications:
1. We should try not resolve all references needed for the target when `--verbose` is not passed. Do we do this now?
2.  We should try to keep `--verbose` as an outputter option rather then using it multiple places in the code.

**Comment by donoghuc** [comment]
Show all config/data fully resolved from cli, config, plugins, defaults, groups etc for a target. Try to implement it where given a `--detail` flag, instead of  returning `Target` strings return an array of fully populated target data. 

If `--detail` cannot be used (or person who implements it feels strongly about new command), we will implement a new sub-command:  `bolt target show <target name>`.
