### ISSUE TITLE
Having an ApplyResult.error() bound to a variable in a plan will cause the next apply() to fail

### ISSUE THREAD

**Issue by jpartlow** [puppetlabs/bolt#1242]
If a plan catches errors, and stores an error instance in a $variable, the next call to apply() will throw a stack overflow attempting to convert that error to_json [here](https://github.com/puppetlabs/bolt/blob/1.30.1/lib/bolt/applicator.rb#L104).

## Expected Behavior
The error parses properly and the apply proceeds.

## Steps to Reproduce
```
jpartlow@work1804:~/work/src/enterprise_tasks$ cat plans/test.pp
plan enterprise_tasks::test () {
  $error = catch_errors() || {
    apply('localhost',) {
      # This apply raises an error which is stored in $error
      file { '/tmp/doesnotexist/foo':
        ensure => directory,
      }
    }
  }
  # The fact that $error is a Puppet::DataTypes::Error causes this next
  # apply to fail when Bolt::Applicator converts the catalog_input to JSON.
  # (PUP-10029)
  apply('localhost') {
    notify { 'this is fine': }
  }
}
```

## Environment
Bolt 1.30.0

## Additional Context
The Bolt::Applicator pulls in [current variables](https://github.com/puppetlabs/bolt/blob/1.30.1/lib/bolt/applicator.rb#L95) into the catalog_input that is then converted [to_json()](https://github.com/puppetlabs/bolt/blob/1.30.1/lib/bolt/applicator.rb#L104). As part of the conversion, the Puppet::DataTypes::Error.to_s is called and causes the stack overflow. I thought this as just a bug in Puppet, and opened [PUP-10029](https://tickets.puppetlabs.com/browse/PUP-10029), but talking with Henrik and Thomas, the to_s() method does work if the current Puppet context has Loaders bound in the current evironment (see [this comment](https://tickets.puppetlabs.com/browse/PUP-10029?focusedCommentId=687822&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-687822)).

I'm not certain if the correct behavior is for Bolt to wrangle environment loaders for this translation, or if the Puppet::DataTypes::Error should be able to convert itself to string without Loaders present.

**Comment by lucywyman** [comment]
We now serialize plan variables as pcore, which should have fixed this but raises a fun new error:
```
{
  "kind": "bolt/pal-error",
  "msg": "undefined method `implementation_class' for #<Puppet::Pops::Types::PObjectTypeExtension:0x0000000004574500>",
  "details": {
  }
}
```
Coming from [this line](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/pops/serialization/to_data_converter.rb#L263). This seems to be happening because the PObjectTypeExtension isn't appropriately getting the implementation class method from the base type. If I do `pcore_type.base_type.implementation_class` in a pry there it has the correct `Puppet::DataTypes::Error` output, rather than erroring. I'm not entirely sure why the TypeExtension isn't accessing the `implementation_class` method, or if that's expected.

**Comment by lucywyman** [comment]
This will be fixed with the next Puppet release
