### ISSUE TITLE
Config options docs should be autogenerated

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#1315]
The configuration options page (documentation/bolt_configuration_options.md) should be auto-generated rather than manually maintained.

**Comment by lucywyman** [comment]
This should be a new rake task under the `docs` rake task that generates the config when the docs rake task is run. As part of this we should move the canonical list of transport options to only be on the transports, and should refer to the transport options in config instead of trying to store transport options there. Config option information for the generated docs should come from the transports themselves, or config for global options. This shouldn't affect when we load defaults - including defaults in the option structure should be for documentation, not for applying the defaults differently.
