### ISSUE TITLE
Provision and destroy cloud resource in a plan through terraform

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#1360]
## Use Case
Currently the terraform inventory plugin is useful if you have long lived terraform infrastructure but not useful when you want to provision or destroy short term infra.

* Spin up a test instance of an application and run bolt based tests.
* Run a plan that completely provisions a demo environment.

## Describe the Solution You Would Like

A module containing a set of puppet plans that expose `terraform apply` and `terraform destroy` functionality. 

## Describe Alternatives You've Considered

An integrated concept of provisioning in the plan language. I don't think we can build this until we have more of the building  blocks in place.

## Additional Context

* This should be added to the `puppetlabs-terraform` module as `terraform::apply` and `terraform::destroy` plans
* What is the interface for passing `vars` to terraform?  The plan should accept a hash of vars to pass on to the `terraform apply` command. What happens if you have a default file and don't pass in vars (answer while implementing)?
* For both plans we should always pass `-auto-approve`, `-no-color`, `-input=false`. We should accept parameters for `-target`, `-var-file`.
* How do resources created or destroyed get added or removed from inventory? We shouldn't automatically add or remove resources from the inventory for the first iteration. A workaround is to use the inventory plugin.
* How can you interact with these resources after they're created? Use both the terraform apply and terraform state plugin. The plan should return any (and only) `outputs` that are defined in the applied file, or else return an empty hash. `resolve_reference` should be exposed as a plan function - see #1365.
* Is there logging we can grab that is helpful?
* Can we use the word apply for something other than `apply`?  `terraform::apply` should be fine...
* How should users manage tf code in their projects? Default to top level of the project? tf dir in project? We should accept a path to the directory where you want to apply.  Default to the directory bolt is run from (`cwd`).
  * We should default to the top-level Boltdir. We'll need to expose the Boltdir to plan - we should put this off until later.

**Comment by ahpook** [comment]
Some comments, informed by recent investigations into terraform integrations:

> What is the interface for passing vars to terraform? The plan should accept a hash of vars to pass on to the `terraform apply` command. What happens if you have a default file and don't pass in vars (answer while implementing)?

It's probably best to avoid backslash-itis and write a file that's passed in to execution with the `-var-file` [command line arg](https://www.terraform.io/docs/commands/apply.html#var-file-foo). This should overlay cleanly on top of the user's default `*.tfvars` files in their working directory. It can be named `whatever.tfvars.json` and [contain json instead of hcl](https://www.terraform.io/docs/configuration/variables.html#variable-definitions-tfvars-files). 

> How should users manage tf code in their projects? Default to top level of the project? tf dir in project?

The convention is to have a subdirectory that contains all the terraform code in it because users often split up larger plans into multiple files and expect that tf will evaluate/execute all of them in directory order. So the bolt plans ought to accept an argument to that directory (though I agree defaulting to `cwd` is probably reasonable).

> logging / code management / execution environment questions 

Check out the [Running Terraform in Automation](https://learn.hashicorp.com/terraform/development/running-terraform-in-automation) guide which talks about these issues

A further iteration might be to make parallel functions that use the tf cloud/tf enterprise API endpoints instead of executing it directly; this would allow remote state and remote execution.

HTH!

**Comment by adreyer** [comment]
@ahpook My assumption has been that if we support the CLI and users can configure that to handle either local or cloud execution.
