### ISSUE TITLE
Singular version of TargetSpec data type

### ISSUE THREAD

**Issue by reidmv** [puppetlabs/bolt#1361]
## Use Case

TargetSpec accepts a single Variant[String, Target] OR an Array of the same, and is understood to best be treated as if it could refer to multiple endpoints.

Sometimes a plan (or task) parameter should accept a single target only. At present, there is no built-in data type to support that.

## Describe the Solution You Would Like

Create and provide a data type defining a _single_ Target(Spec).

`Boltlib::SingleTargetSpec`?

## Alternatives Considered

Considered parameterizing TargetSpec, e.g. with size constraints such as `TargetSpec[1]`. Seems infeasible in the type system implementation.

Considered changing Bolt CLI or other interfaces to pre-convert target information, so that type definitions can just worry about Target and Array objects. Seems to put more burden on the user though.

See https://tickets.puppetlabs.com/browse/BOLT-1363.

**Comment by adreyer** [comment]
Fundamentally I don't this level of validation with the puppet type system.
1.  The bolt inventory is fundamentally dynamic.
2.  Strings may resolve to a single target or a group of targets. 

We can make a weak validator as in #1363 which is useful to fail fast in some situations but plan authors can not rely on a `SingleTargetSpec` to actually return a single target `get_target`.  I don't think weak validator should ship with bolt since plan authors cannot rely on it. They will still have to handle cases where the type did not correctly validate.

We've done some magic with how `run_plan` handles `TargetSpec` and `Optional[TargetSpec]` but I don't think we can rely on that magic for validation since it means this type would not work well in other compound types like `Variant[Pattern, TargetSpec]`, `Any`, or `Hash[String, TargetSpec]`.

**Comment by reidmv** [comment]
Making Target objects easily and intuitively passable from the CLI could be a reasonable solution. The ideal user experience is a transparent one, where the user doesn't have to do anything special and just passes their server name, as per usual.

For now I find enough utility in rough type checking that I'll [implement it in the module I need it in](https://github.com/puppetlabs/puppetlabs-pe_xl/blob/01e3adb1e905ca024931daac9d59b424e6b09e45/types/singletargetspec.pp). Looking forward to any solution that is robust enough to be built into Bolt directly.
