### ISSUE TITLE
Support "external" facts in apply blocks.

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/bolt#1431]
How should bolt expose external facts when compiling apply blocks

## TODO
* Investigate if you had a manifest used from puppetserver that relied on external facts, is there a way to make that same manifest work with Bolt?
* The outcome of this is likely that we need to expose more ways to control trusted data

**Comment by lucywyman** [comment]
[Puppet 6.11 supports](https://puppet.com/docs/puppet/latest/release_notes_puppet.html#release_notes_puppet) (experimentally) a `trusted_external_command` setting:
> The value for trusted_external_command is a path to an executable command that can produce external trusted facts. The command must:
>    * Take the name of a node as a command-line argument.
>    * Return a JSON hash with the external trusted facts for this node.
>    * Exit with a non-zero exit code for unknown or invalid nodes.

This sets the `$trusted['external']` key. If we set the trusted_external_command setting in Puppet to whatever the user configures when using Bolt, then this JustWorks:tm:. The only small caveat is that `retrieve_trusted_external` is a [private method](https://github.com/puppetlabs/puppet/blob/388ce62275e40bffc8c48def044473770d68c417/lib/puppet/context/trusted_information.rb#L77) on `Puppet::Context::TrustedInformation`, which typically gets called from the [local trusted info instantiator](https://github.com/puppetlabs/puppet/blob/388ce62275e40bffc8c48def044473770d68c417/lib/puppet/context/trusted_information.rb#L70) but since we instantiate the class on our own, we need to manually call it. We can do this by using `Puppet::Context::TrustedInformation.send(:retrieve_trusted_external, target.name)`, or try to make `target.name` a node object so we can just call `Puppet::Context::TrustedInformation.local`.

We'll need to expose a `trusted_external_command` configuration option for Bolt which accepts a string that's the path to a single script to run to get trusted external facts.
