### ISSUE TITLE
Double console log lines when console log level config is changed

### ISSUE THREAD

**Issue by desolat** [puppetlabs/bolt#1435]
## Describe the Bug
When there is a `console:` config block with a `level:` lower than the default `warn` level in `bolt.yaml` the log lines starting with `Starting` or `Finished` are double-logged to the console.

## Expected Behavior
No dublicated log lines on the console.

## Steps to Reproduce
1. Configure in `bolt.yaml`:

```
  console:
    level: notice
```

## Environment
 - Version 1.38.0
 - Ubuntu 18.04

**Comment by donoghuc** [comment]
Looking back I forgot to write *why* this is expected behavior, but this came up on PR review for this. https://github.com/puppetlabs/bolt/pull/955#discussion_r281778744

**Comment by desolat** [comment]
Sorry, but I don't understand why this expected (in the sense of user acceptable or expected by the user) behaviour. Could you elaborate on this?

**Comment by adreyer** [comment]
The problem is that the bolt logger is serving two different purposes.
1. It allows users to view everything that happened during a bolt execution this means it can be directed at a file to provide auditing or latter debugging.
2. It is used as a supplement to the main outputter system in bolt to handle warnings and errors, data that does not fit into the outputters format(ie not part of a single JSON object) or provide more detailed output when set to a higher level for debugging.

notice exists primarily for the first use case. To make sure that every action is saved to a file we need to send it to the logger regardless of whether it's getting printed. 

I agree that this is not an optimal user experience but it is expected behavior. I don't think we'll tackle solving it until we refactor how bolt handles output, which probably won't be for a while.
