### ISSUE TITLE
Specify `run-as-command` without a `run-as` user

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#1506]
## Use Case
In high-security environments, users may only have access to certain commands and code-paths using sudo. Users can't escalate to the root user using sudo, but can execute certain commands. In this case it's useful to specify `run-as-command` so that Bolt commands, scripts, tasks, etc. can be run using sudo when needed. However the requirement that `run-as` be specified means that users can't actually execute, since there's no user to specify. Specifying an empty string may not work for some `run-as-command` commands, and specifying the same value for `user` and `run-as` prevents the escalation string from being added.

## Describe the Solution You Would Like
There are a few solutions to this:
1. Suggested by @logicminds: add a new `--with-sudo` option which will skip `run-as` checking and set `run-as` to nil.
2. We could also just make `run-as` option when specifying `run-as-command`, and only add it if it's configured. We would still need to escalate based on `run-as-command` being present without `run-as`.

**Comment by logicminds** [comment]
After validating if the fix above would work I ran into other issues around the lifecycle of the temporary script directory that is related to the issue above.  Please note my code above is not a final solution. 

```yaml
# bolt.yaml
ssh:
  tmpdir: /home/bolt_svc/tmp
  script-dir: 'bolt-scripts'
```

The script lifecycle can be defined as:

1. `bolt task run puppet_agent::version --user bolt_svc -t puppetsrv1.companyx.com`
2. login as bolt_svc user to puppetsrv1.companyx.com
3. [Create](https://github.com/puppetlabs/bolt/blob/master/lib/bolt/transport/sudoable/tmpdir.rb#L20) the script-dir under the tmpdir (without sudo)
4. [Upload](https://github.com/puppetlabs/bolt/blob/master/lib/bolt/transport/sudoable.rb#L101) the script to the script-dir /home/bolt_svc/tmp/bolt-scripts/puppet_agent_version.sh
5. [Chown](https://github.com/puppetlabs/bolt/blob/master/lib/bolt/transport/sudoable/connection.rb#L33) the script (without sudo)
6. [Execute](https://github.com/puppetlabs/bolt/blob/master/lib/bolt/transport/sudoable.rb#L128) (Code that needs to be fixed to allow sudo without user escalation)
7. [Delete](https://github.com/puppetlabs/bolt/blob/master/lib/bolt/transport/sudoable/tmpdir.rb#L49) the script-path (with sudo)

The big problem with the delete step is that it is run with sudo when it should not always be.  Because in a secure environment any command prepended with sudo must be whitelisted for that specific user ahead of time.  So running `sudo rm -rf /home/bolt_svc/tmp/bolt-scripts/ ` directory fails during the bolt run due to command not being whitelisted.  But since the same user created the directory there is no reason to run with sudo.  So we need the delete step to be more flexible and only use sudo if the the current user did not create it.

**Comment by lucywyman** [comment]
@logicminds Is this still something you need?

**Comment by logicminds** [comment]
Yes.  I would consider this a major bug / feature that should be fixed.
