### ISSUE TITLE
Catalog compile fails when variable in plan scope has the same name as a Target fact

### ISSUE THREAD

**Issue by donoghuc** [puppetlabs/bolt#1725]
## Describe the Bug
If in the plan scope (outside of an apply block) a variable exists that happens to have the same name as a fact on the Target you are targeting for apply the apply block fails to compile. 

## Steps to Reproduce
```
plan test(TargetSpec $targets){
  $target = get_target($targets)
  $foo = 'bar'
  $target.add_facts('foo' => 'bar')
  return apply($target){
    notify {"$facts":}
  }
}
```

```
cas@cas-ThinkPad-T460p:~/working_dir/control-repo$ bolt plan run test --modulepath site-modules --targets localhost
The documented parameter 'foo' does not exist in plan signature
Starting: plan test
Starting: apply catalog on localhost
Finished: apply catalog with 1 failure in 1.91 sec
Finished: plan test in 1.91 sec
Failed on localhost:
  Apply failed to compile for localhost: Cannot reassign variable '$foo' on node localhost
Failed on 1 target: localhost
Ran on 1 target
```
## Additional Context
This line is where it fails https://github.com/puppetlabs/bolt/blob/master/lib/bolt/catalog.rb#L75
So it looks like the facts are in the same scope? https://github.com/puppetlabs/puppet/blob/f5d2b330391d706a864357972312ca5cadf8441f/lib/puppet/pal/pal_impl.rb#L373

**Comment by lucywyman** [comment]
Expected behavior: The fact should take precedence over the plan var or target var, and we should warn that that's what we will use. Reasoning is that it's easier for users to rename a var within a plan than it is to rename a fact and that the contract when using facts in a manifest is between the ecosystem and the manifest while for plan vars the contract is only between the plan and the manifest within the plan.
Question: How does an ENC behave when it sets a var with the same name as a fact? You get a warning and the fact overrides it.

**Comment by donoghuc** [comment]
So ideally a Target facts takes precedence over plan variables *and* Target variables? 

What is the precedence of Target variables? Currently plan variables take precedence over target variables https://github.com/puppetlabs/bolt/blob/master/lib/bolt/catalog.rb#L75 (which seems kind of counter-intuitive to me if target facts take precedence).

**Comment by lucywyman** [comment]
> So ideally a Target facts takes precedence over plan variables and Target variables?
Yeah - I see the unintuitiveness around a target-data precedence sandwich, but I think the precedence is more about predictability and ease of overriding than it is about where something is defined. Facts should take precedence because you could be using ecosystem code that refers to facts and makes assumptions about their values, and if an individual plan overrides that it would behave strangely and be hard to debug. Nick phrased it well: facts are a global contract, while plan vars are a local contract. Plus, it's easy to change a var name in your plan if there's a conflict, but hard to change a fact name.

I think that plan vars should still override target vars for the same reason. As a plan author, you don't know what vars a user is going to have set in their inventory, and you are going to make assumptions about what that variable is set to. Having a plan fail because a user has a specific var set on a target in inventory that happens to conflict would similarly be hard to debug, but having plan vars override target vars makes their behavior much more predictable by the plan author.

Last thing is that I think the intuitive precedence for facts, vars, and plan vars is going to be different depending on the use case, and I suspect no matter what we choose it will break someone's expectations. But this precedence at least feels defensible.
