### ISSUE TITLE
BoltSpec should be able to mock Puppet functions

### ISSUE THREAD

**Issue by op-ct** [puppetlabs/bolt#1812]
## Use Case

I have plans that use Puppet functions.

I want to test these plans with BoltSpec, but I can't because BoltSpec doesn't mock functions yet.

## Describe the Solution You Would Like

A new method in BoltSpec that can mock Puppet functions.

## Additional Context

* The "normal" rspec-puppet approaches to mocking Puppet 4+ functions don't work, because Bolt compiles plans using its own separate Puppet compiler (accessed via [`Bolt::PAL`](https://github.com/puppetlabs/bolt/blob/master/lib/bolt/pal.rb)).
* In the #bolt slack, @nicklewis pointed out [`Puppet::Parser::EnvironmentCompiler#add_function_override`](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/parser/environment_compiler.rb#L23-L40) as an example of the kind of functionality that we'd have to add to the Bolt compiler for it to support a function-mocking BoltSpec function. ([slack discussion](https://puppetcommunity.slack.com/archives/C7GP57T50/p1588973932467300))

## Describe Alternatives You've Considered

We discussed other approaches in the #bolt slack that ranged from "impossible" to "effectively impossible":

1. **Adding a function stub with `pal.evaluate_string` before `example.run`.**
     This would override the mocked function with a pure Puppet language stub just before compiling the example, like the [rspec-puppet `let(:pre_condition) { "function foo::bar{ return 'blah' }" }` technique](https://github.com/rodjek/rspec-puppet/issues/102#issuecomment-372658544) for mocking Puppet 4+ functions. ([slack discussion](https://puppetcommunity.slack.com/archives/C7GP57T50/p1588974422472500)).
    
    :no_entry_sign:  This approach won't work in BoltSpec. The life cycle of the relevant PAL object is bound to the `BoltSpec::Plans` module's [`run_plan` method](https://github.com/puppetlabs/bolt/blob/master/lib/bolt_spec/plans.rb#L221), and there's no opportunity to get at the compiler to before the example runs.

   It would also limit the stubbed function's definition to the Puppet language. ([slack discussion](https://puppetcommunity.slack.com/archives/C7GP57T50/p1588974422472500))

2. **Substituting the compiler object with a (wrapped) mock + expectation for the function**
    Since we can't get at anything inside `run_plan`, intercept the Puppet compiler object _before_ `run_plan` gets hold of it: set an RSpec expectation for the compiler object's constructor, use `.and_wrap_original` to mock it, and stub out the mocked function call by setting another expectation on the mocked compiler object (returning a suitable object with `.and_return`).   @hlindberg originally suggested this approach to mock complex Puppet 4 functions in rspec-puppet. (https://gist.github.com/hlindberg/8c250c54f5adb76679576ae5cffff868).

    :no_entry_sign: Mocking _Bolt's_ compiler like this _might_ not be impossible, but the process would be so difficult and fragile, it pretty much is. ([slack discusson](https://puppetcommunity.slack.com/archives/C7GP57T50/p1588974901477000))

3. **Adding a stub version of the function to the front of the modulepath**
    @nicklewis suggested this as a workaround to the other approaches.

    :no_entry_sign::question:  Placing any path before the one that contains the plan under test makes BoltSpec/respc-puppet/PAL/something unable to find the plan, resulting in a `Bolt::Error: Could not find a plan named <plan_name>` failure.  It's not clear why this happens. ([slack discussion](https://puppetcommunity.slack.com/archives/C7GP57T50/p1588975057479300))

**Comment by reidmv** [comment]
My team was about to file a new issue (text below), looks like this is the same as our request.

----

When writing a unit test for a plan, we need to be able to allow or expect custom function calls as well as task and plan runs. At this moment, this is unfortunately not possible using BoltSpec. This makes unit tests of plans less useful since a unit test for a plan currently basically consists of just allowing or expecting task or plan runs in a specified order.

The module https://github.com/puppetlabs/puppetlabs-peadm contains many plans which we would like to simplify testing for by mocking functions. As an example, in this unit test we would ideally just mock the peadm::file_content_upload() function. Because that isn't possible, we are left to dig deep into the function's innards as a workaround.

-----

Thought: could we rig this up by injecting a new/custom function loader, which loads any mock functions first?
https://www.rubydoc.info/gems/puppet/Puppet/Pops/Loader/BaseLoader

**Comment by glangloi** [comment]
I am currently struggling with this exact issue, so just wanted to add a note saying I think this would be super helpful in maintaining clean tests.

**Comment by dionysius** [comment]
kindly asking to reopen this issue. Seems to be closed and forgotten...
