### ISSUE TITLE
Don't fail when looking up data outside an apply block from a hiera.yaml that includes interpolations

### ISSUE THREAD

**Issue by magnuslarsen** [puppetlabs/bolt#1835]
Hi! Thanks for including the `lookup()` function, for outside apply blocks!

I am however stopped by this error, upon using it:
```json
{
  "kind": "bolt/pal-error",
  "msg": "Interpolations are not supported in lookups outside of an apply block: Undefined variable 'domain' (file: /home/user/git/control-repo/hiera.yaml, line: 10)",
  "details": {
  }
}
```
It's not uncommon to use variable expansion in Hiera config, so I think it should be supported fully, or at very least be ignored, so a lookup works, if a yaml file was specified later in the hierarchy without variable expansion (e.g. `common.yaml`), and containing the key in the `lookup('key')`

Tested with Bolt 2.10.0

**Comment by lucywyman** [comment]
A few options:
- automatically make plan params available to interpolations. Nested plans?
- Provide a means for specifying interpolation variables (config? CLI?)
- Lookup from special env vars

- This can't be in the same hierarchy as within apply blocks because `certname` doesn't have meaning outside of a per-target block, ie. apply
- Use case: I want to use data in dev/prod environment and want to use hiera to look it up because that's what I do elsewhere
- For the above use case specifically, just *having* a separate hierarchy (from apply) may be sufficient

First iteration:
- Create a new hierarchy separate from the apply hierarchy
  - Hierarchies are currently per-project
  - This should be a separate key in `hiera.yaml` called `plan-hierarchy` which is data to be used in the plan. This should share defaults such as `version` and `datadir` with the general `hierarchy`
- Getting started with Hiera document that describes using Hiera with Bolt, if you don't use Hiera or Puppet.

**Comment by benridley** [comment]
@lucywyman Does this addition have a corresponding fix in regular Puppet? We've noticed after adding a plan_hierarchy to our hiera.yaml that our Puppet Server will no longer compile, saying hiera.yaml has an unknown key. We're happy to plan an upgrade to our PE installation, but just want to confirm this is in? Cheers!

**Comment by benridley** [comment]
Ahh all good, I found it in https://puppet.com/docs/pe/2019.8/release_notes_pe.html. 

Time to upgrade :)
