### ISSUE TITLE
Add support for downloading files from targets

### ISSUE THREAD

**Issue by nmaludy** [puppetlabs/bolt#1868]
## Use Case
As a Bolt user there are times where i need to retrieve a file from a remote host/target and download it onto my Bolt control node. Examples:
- We operate RHEL servers as part of our infrastructure. The RHEL support tool `sosreport` is used on hosts to collect diagnostic info that you upload to your support case. I would love to automate this process with Bolt by initiating a command from my machine and it goes out to a list of hosts, runs `sosreport` downloads the bundles (tar.xz files) and then uploads them to the Red Hat support case.
- Similar use case for Graylog Support, they have a tool called `apollo` that generates support bundles that we would like to automate the collection and upload for.
- I also have a use case where i want to understand what the "current contents" of a file are and diff them between hosts. Example: I have a Production server and a Staging server that are exhibiting different behavior when writing to the database. I want to grab the database configs from both hosts and diff the configs to see if they are the same.
- We want to perform a Database / Application backup of a remote host, then download that backup so we can place it in the proper storage location. In this case it would be a `download` followed by an `upload` most likely, unless we were running Bolt from the storage server. Might also be an interesting use case for a `transfer_file` function. Although, the `download_file` and `upload_file` workflow is perfectly acceptable.

## Describe the Solution You Would Like
Would love to see a function `download_file()` that works similarly to `upload_file()` except in reverse.

The "hard" part here is answering the question "if i have multiple targets, where do i put the files". I'm open to suggestions on this, but my "gut" tells me to drop them into a directory tree where the directory names correspond to the names of the targets. Example:

```
$ bolt download /var/log/sosreport.tar.gz --targets host1,host2,host3 destination=./redhat-support-12345
.... # Bolt does its thing

$ tree ./redhat-support-12345/
./redhat-support-12345/
|-- host1
|   `-- sosreport.tar.gz
|-- host2
|   `-- sosreport.tar.gz
`-- host3
    `-- sosreport.tar.gz

3 directories, 3 files
```

Could also do something where the full directory path is included in the destination (maybe an option to turn this on/off):
```
$ bolt download /var/log/sosreport.tar.gz --targets host1,host2,host3 destination=./redhat-support-12345 full_path=true
.... # Bolt does its thing

$ tree ./redhat-support-12345/
./redhat-support-12345/
|-- host1
|   `-- var
|       `-- log
|           `-- sosreport.tar.gz
|-- host2
|   `-- var
|       `-- log
|           `-- sosreport.tar.gz
`-- host3
    `-- var
        `-- log
            `-- sosreport.tar.gz

9 directories, 3 files
```

## Describe Alternatives You've Considered
I've thought about writing my own task that outputs the file contents as `base64` and then decode and write the data to a file. This seemed like a really slow and clunky option.

## Additional Context
Looks like Ansible supports this in the form of their [`fetch`](https://docs.ansible.com/ansible/latest/modules/fetch_module.html) and [`slurp`](https://docs.ansible.com/ansible/latest/modules/slurp_module.html) "modules"

**Comment by lucywyman** [comment]
Notes:
- When downloading the user specifies a destination directory (this *must* be a directory) and each target has its own subdirectory that the downloaded file gets downloaded to
  - For the command, this needs to be predictable
  - For the case where you're downloading it then doing something with the file users can get the object / path from the resultset and operate on it.
  - What should we do when a target doesn't have a valid file/directory name? URLEncode the url, and encourage users to give targets a 'name' that is readable if they care about the directory name.
  - What happens if you specify the destination as a single file? Create a directory as normal. The destination for download_file will always be a directory.
  - We could potentially (future work) have a plan function where each target has a computed destination (similar to run_task_with).
  - CLI + puppet plan function + yaml plan step in scope for this ticket
