### ISSUE TITLE
Pull external ssh transport into a separate transport class

### ISSUE THREAD

**Issue by beechtom** [puppetlabs/bolt#1938]
## Use Case
Currently, the external SSH transport is folded into the `Bolt::Transport::SSH` class even though our docs describe it as a separate transport. This results in the SSH transport having a list of config options that may or may not be available depending on whether the `ssh-command` option is set. Because of this, the reference docs for the SSH transport are more complicated than the other transports, as we need to mark which options are supported when using the `ssh-command` option.

We should create an external SSH transport that is wholly separate from the existing SSH transport. This would still require users to explicitly opt-in to using the transport, while allowing us to set a reasonable default value for the SSH command and simplify our documentation for which options are available for the external SSH transport.

**Comment by lucywyman** [comment]
The real issue here is separating SSH config that's supported by external or not. It might make more sense for this to be a documented separation than an actual separation in code. In code, this would just be a master list of options with each transport listing what options it applies to.

This should be made part of #1888 

Should we have a separate config flag for turning on external ssh, rather than using ssh-command? This would allow us to set a default for ssh-command and not overload this flag with 2 meanings.

Start with just modifying this in the config object and we can later separate out the transports.
- [ ] Update 1888 config building
- [ ] Ask in slack whether people mind specifying external ssh as part of the protocol
- [ ] Add `external-ssh` in the `ssh` transport config to enable using external-ssh. `ssh-command` should default to `ssh`.

Repeating options in docs is not necessarily a bad thing, it's simpler for people.
