### ISSUE TITLE
Allow "su" escalation using the command line

### ISSUE THREAD

**Issue by gittygoo** [puppetlabs/bolt#2041]
## Use Case
Sudo escalation currently seems possible, however "su" escalation not and run-as-command seems to be configurable only through yaml and not via a command parameter

**Comment by adreyer** [comment]
We're trying to not bloat the CLI commands and help text any further by exposing options that aren't commonly used. Is there a reason why configuring this with inventory won't work?

**Comment by gittygoo** [comment]
We are currently using bolt for one-time-off commands on our in-house developed application, for this we have a list of targets in our app (these can change quite often). The app server triggers a second server to then execute the commands on the target. 

If we can pass all as parameters this works perfectly as one command, if not, that involves multiple steps... (Temporarily creating files on the second server, triggering the command, etc... )

**Comment by adreyer** [comment]
Because we're also struggling with users not being able to easily discover the CLI flags they need. The fact that most connection related options are exposed is a legacy of early bolt development when we didn't have any configuration files. 

You can set the run-as-command at the top level of inventory and it will be used for all targets. If you can't use an inventory file from the server it can pass inventory data as an environment variable like:
```BOLT_INVENTORY='{"config": {"ssh": {"run-as-command": "su ..."} } }' bolt task run .... ```

**Comment by gittygoo** [comment]
@adreyer Wouldn't that cause potential troubles when running 2-3 commands in parallel? Some sort of "race condition" for getting the contents of BOLT_INVENTORY env var? Would have to test this i guess.. 

Following your method i guess i would also have to pass the BOLT_INVENTORY variable as empty for specific targets that do not require it to again, avoid that "race condition" for the env var contents
