### ISSUE TITLE
Read command to run with Bolt from a file

### ISSUE THREAD

**Issue by nicklewis** [puppetlabs/bolt#2125]
## Use Case

On certain systems, particularly network devices, files can't be written and therefore `bolt script run` doesn't work. In that case, it's useful to be able to run a long, multi-line script as a command.

## Describe the Solution You Would Like

`bolt command run @file.txt` should read the command run a file named `file.txt`. If the file doesn't exist or can't be read, it should error.

**Comment by jpogran** [comment]
Testing this approach in PowerShell proves we can't use `@` without escaping it because that's the `spaltting operator` :

```
➜ function bolt { param($command) "I'm reading content of $Command"; gc $command }
➜ bolt @foo.txt
ParserError:
Line |
   1 |  bolt @foo.txt
     |        ~~~~
     | The splatting operator '@' cannot be used to reference variables in an expression. '@foo' can be used
     | only as an argument to a command. To reference variables in an expression use '$foo'.
```

You can use the backtick escape character to get PowerShell to skip using `@` and have it successfully pass down:

```
➜ bolt `@foo.txt
I'm reading content of @foo.txt
Get-Content: Cannot find path 'C:\Users\james\src\puppetlabs\bolt\@foo.txt' because it does not exist.
➜
```

That suffices the raw `bolt` command, if leaves a little to be desired in UX.

Using PowerShell Language features, we could have the cmdlet handle it without using `@`. A super naïve approach follows:

```
➜ function bolt {
>>   param(
>>     $command
>>   )
>>   if(Test-Path $command){
>>     "I'm reading content of $Command";
>>     $text = gc $command
>>     # invoke bolt
>>   }else{
>>     # invoke bolt
>>   }
>> }
```
