### ISSUE TITLE
Bolt task should allow 'run_as' with restrictive sudo rules

### ISSUE THREAD

**Issue by breca** [puppetlabs/bolt#2139]
## Describe the Bug
Similar to https://github.com/puppetlabs/bolt/issues/1732 and https://github.com/puppetlabs/bolt/issues/1506.

Currently, when executing a task that requires to run_as a different user, Bolt scp's the task to remote nodes and then attempts to chown the tmpfile, presumably so that the task can be read by the run_as user.

Out of the box, it performs this chown by executing `/bin/sh -c cd; chown -R <user>:<group> /tmp/<tmpfile>` via sudo.

If the user in question does not have sudo access to `/bin/sh`, this results in:

```
Could not change owner of '/tmp/94012c72-63e7-43b2-90a2-a4ba6cdf7232' to <user>: Sorry, user <bolt_user> is not allowed to execute '/bin/sh -c cd; chown -R <user>:<group> /tmp/94012c72-63e7-43b2-90a2-a4ba6cdf7232' as root on <node>.
```

Unfortunately allowing users sudo access to /bin/sh is effectively handing over the keys to the kingdom and is impractical for high-security environments.

## Expected Behavior
I expect that we would be able to either define a chown command in inventory or (my preference) that Bolt would directly execute `sudo <path>/chown` so that administrators could capture that in their sudoers. Alternatively, Ansible gets around this by using `setfacl`, so thats another approach that is arguably a lot cleaner.

## Steps to Reproduce
1. Have a user that has explict access to a limited number of sudo commands (not including /bin/sh)
2. Execute a task with a `run_as` argument

## Environment
 - Version 2.9.0
 - Platform RHEL7.x

**Comment by adreyer** [comment]
Is the `run-as` value another non-privileged user or are you trying to  `--run-as root` in this case?

**Comment by breca** [comment]
It's a regular, non-privileged user.

**Comment by RobinOphalvens** [comment]
Not stale.

Currently, we're manually supplying `sudo` in our custom tasks as using `--run-as root` requires us to give the non-privileged user - bolt in our case - the following sudo rules (where `/home/bolt/tmp` is the tmp dir):

```shell
bolt ALL=(ALL) NOPASSWD:/usr/bin/sh -c cd; chown -R root\:0 /home/bolt/tmp/*
bolt ALL=(ALL) NOPASSWD:SETENV:/usr/bin/sh -c cd; /home/bolt/tmp/*
bolt ALL=(ALL) NOPASSWD:SETENV:/usr/bin/sh -c cd; /home/bolt/tmp/*/*/*/*
bolt ALL=(ALL) NOPASSWD:/usr/bin/sh -c cd; rm -rf /home/bolt/tmp/*
```

As @breca remarks, this basically gives the user keys to the kingdom since you are able manipulate these rules by creating an arbitrary file under `/home/bolt/tmp` with some malicious commands which you can then execute, allowing you to run anything as that user. This is especially bad news when you require root for package or service management, for example. 

While this does require you being able to log into the machine and get access to the bolt user, preventing this mechanism all-together would be a cleaner solution imho.

We're considering making retrofitted forks of built-in Bolt tasks such as `package` and `service` where `sudo` is used for each command that requires the elevated privileges, which we can then cleanly capture in our sudo rules and ultimately skip `--run-as` .

I'd be interested to see if @breca 's proposed solutions would be viable. Despite my limited knowledge in Ruby, I'd be happy to help out where possible! Alternatively, I'm also open for advice if anyone has a cleaner method in mind :)

Thanks in advance!

**Comment by donoghuc** [comment]
I'm having a hard time parsing out exactly what issues you are having here. Is the root of the issue that you dont want to run the chown as root? I think the following information would be helpful for me:

1. The commend below seems to me to be the purpose of the `run-as-command` configuration setting https://www.puppet.com/docs/bolt/latest/privilege_escalation.html#how-run-as-works maybe you could provide and example of how you intend to modify the builtin tasks to support your use case? 
```
We're considering making retrofitted forks of built-in Bolt tasks such as package and service where sudo is used for each command that requires the elevated privileges, which we can then cleanly capture in our sudo rules and ultimately skip --run-as .
```
2. It looks like you are configuring a dedicated bolt user on the remote system which is a good step, ultimately the current design requires arbitrary execution for that user as described here https://www.puppet.com/docs/bolt/latest/privilege_escalation.html#escalating-privilege-must-be-generalized

**Comment by RobinOphalvens** [comment]
Apologies, I should have been a bit more clear in my previous comment. :slightly_smiling_face: 

Allow me clear up the confusion with a second attempt.

The main point I was trying to make is more along the lines of "this works, but it would be nice if we could improve it a bit further" instead of "this doesn't work at all".

As you correctly noticed, we're using a dedicated bolt user on the remote system. However, I would like to limit the amount of privileged actions that this bolt user can perform as much as possible. This means a restrictive sudo environment where we create a sudo rule for each command where it is required. So no `bolt ALL=(ALL) NOPASSWD:ALL` whatsoever.

For a simple `bolt command run` or `run_command` in plans, you can do something like this:

```shell
bolt command run 'sudo dnf install -y mypackage'
```

alongside the following sudo rule:

```
bolt ALL=(ALL) NOPASSWD:/usr/bin/dnf install -y mypackage
```

Nice, easy and will work just fine. The interesting part, however, arises when you start using `--run-as root`, which you'll usually have to do when you want to run tasks such `package` or `service`.

As you mentioned, [the privilege escalation documentation](https://www.puppet.com/docs/bolt/latest/privilege_escalation.html#escalating-privilege-must-be-generalized) indeed warns that limited priv escalation will put you in a bit of conundrum.

If you still decide to go with a restricted sudo environment, you'll need the following rules for the user on the remote host:

```
bolt ALL=(ALL) NOPASSWD:/usr/bin/sh -c cd; chown -R root\:0 /home/bolt/tmp/*
bolt ALL=(ALL) NOPASSWD:SETENV:/usr/bin/sh -c cd; /home/bolt/tmp/*
bolt ALL=(ALL) NOPASSWD:SETENV:/usr/bin/sh -c cd; /home/bolt/tmp/*/*/*/*
bolt ALL=(ALL) NOPASSWD:/usr/bin/sh -c cd; rm -rf /home/bolt/tmp/*
bolt ALL=(ALL) NOPASSWD:SETENV:/usr/bin/env * # required starting from bolt 3.27.1
```

which you can then test with:

```
bolt task run --no-host-key-check -u bolt --private-key ./some-priv-key service::linux action=status name=sshd --targets my-remote-host --tmpdir /home/bolt/tmp --log-level trace --run-as root
```

With that enormous background context aside, I can finally get to the main point of my previous comment :slightly_smiling_face: 

Let's zoom in on `bolt ALL=(ALL) NOPASSWD:SETENV:/usr/bin/sh -c cd; /home/bolt/tmp/*` . With this rule, you basically get root access to a machine if you somehow get a shell to the bolt user on the remote host.

A reproduction example (with some of the ls output omitted):

```shell
[bolt@sandbox tmp]$ pwd
/home/bolt/tmp
[bolt@sandbox tmp]$ mkdir /home/bolt/tmp/test
[bolt@sandbox tmp]$ echo -e "#/bin/sh \n touch /root/pwntest\n ls -l /root/" > /home/bolt/tmp/test/pwntest.sh
[bolt@sandbox tmp]$ chmod u+x /home/bolt/tmp/test/pwntest.sh
[bolt@sandbox tmp]$ sudo -n -u root sh -c cd\;\ chown\ -R\ root:0\ /home/bolt/tmp/test
[bolt@sandbox tmp]$ sudo -n -u root sh -c cd\;\ /home/bolt/tmp/test/pwntest.sh
-rw-r--r--. 1 root root      0 Dec 11 22:15 pwntest
```

Again, this requires you being able to open a shell with the bolt user on the remote host in the first place. One probably has bigger problems if someone with malicious intentions already got that far.

**Finally, the key question which both I, and I think OP as well, have:** would it technically be possible to perform the privilege escalation without giving the non-privileged user on the remote host access to /bin/sh, or without requiring the above-mentioned sudo rules?

If the answer is "no" or "the current design currently requires arbitrary execution", as you mentioned earlier, that's all right. I can work with that :slightly_smiling_face: . Then we'll simply make sure the bolt user on remote hosts is as isolated as possible. Having the additional layer of defense would have been neat.

Lastly, regarding the first point you brought up. 

> maybe you could provide and example of how you intend to modify the builtin tasks to support your use case?

My idea would be that I create a copy of the built-in `package` task where each `yum` command is prefixed with sudo. This would allow me to get rid of my problematic sudo rules all-together and circumvent the usage of `--run-as root` as well. As a result, I'd be able to simply run `bolt task myproject::package` where the script itself which will perform the privilege escalation based on the fine grained sudo rules on the system.

Phew, apologies for the giant essay. Once again, thanks for taking your time to go through this! Cheers!

**Comment by tj-cisco** [comment]
@breca this is still an open issue can you reopen this bug please?

**Comment by breca** [comment]
I sure can't, feel free to open your own issue and reference this one though.
