### ISSUE TITLE
Receive "unable to get local issuer certificate" error when attempting to run bolt puppetfile install

### ISSUE THREAD

**Issue by rychannel** [puppetlabs/bolt#2171]
## Describe the Bug

When I run bolt puppetfile install, I get the following error:

SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)

## Expected Behavior
I expect the modules to actually install

## Steps to Reproduce

1. Run bolt puppetfile install from Windows

## Environment
 - Version 2.27.0
 - Platform: Windows 10

**Comment by jpogran** [comment]
Hi @rychannel thanks for the report. Are you using a proxy? Can you paste output from an example run?

**Comment by rychannel** [comment]
I found a support article on the Puppet Support site that said how to fix it.

**Comment by jpogran** [comment]
That is great! Does that mean I can close this issue, or is there anything else we can help with?

**Comment by rychannel** [comment]
Yep

**Comment by jpogran** [comment]
The crux of the issues lies in these lines: https://github.com/puppetlabs/bolt/blob/b097bd10f94016a2115fb82e1bd6613ac9aee5b3/pwsh_module/pwsh_bolt_internal.ps1#L23-L25

We set these inside the bolt function, but instruct users that they can override it by setting it directly in the shell like this:

```
❯ $env:SSL_CERT_FILE = 'C:\path\to\ssl\cert.pem'
❯ bolt puppetfile install
```

This will never work, because the function always sets those variables. The long term fix is to have the function first check if those variables are set, and if set do not assign the default value to them.

The short term workaround is to have the user copy the following function and add it to their `$PROFILE`, which will override the function declared in the PuppetBolt module, and then delete these lines when the fix lands

```
function bolt {
  $fso = New-Object -ComObject Scripting.FileSystemObject

  $script:BOLT_BASEDIR = (Get-ItemProperty -Path "HKLM:\Software\Puppet Labs\Bolt").RememberedInstallDir
  # Windows API GetShortPathName requires inline C#, so use COM instead
  $script:BOLT_BASEDIR = $fso.GetFolder($script:BOLT_BASEDIR).ShortPath
  $script:RUBY_DIR = $script:BOLT_BASEDIR
  # Set SSL variables to ensure trusted locations are used
   if(!$env:SSL_CERT_FILE){
    $env:SSL_CERT_FILE = "$($script:BOLT_BASEDIR)\ssl\cert.pem"
  }
  if(!$env:SSL_CERT_DIR){
    $env:SSL_CERT_DIR = "$($script:BOLT_BASEDIR)\ssl\certs"
  }
  &$script:RUBY_DIR\bin\ruby -S -- $script:RUBY_DIR\bin\bolt ($args -replace '"', '"""')
}
```

**Comment by lucywyman** [comment]
There are a few different ways we could approach this:
- Letting the user set SSL_CERT_DIR
- Letting the user override Puppet SSL settings
- Or, maybe best, we could allow the user to specify an additional trusted CA

Or, it seems there may be an SSL_CERT_DIR directory where a user could add certs they want to use. Does adding the cert to that directory work?

**Comment by npwalker** [comment]
I think this is the instructions for how to workaround this for puppet agent.  https://support.puppet.com/hc/en-us/articles/115000390993-Add-certificates-to-the-Puppet-certificate-bundle-in-Puppet-Enterprise-2015-2-x-to-2019-0-x
