### ISSUE TITLE
Invoke-BoltCommand fails to run PowerShell command with mixed quotes

### ISSUE THREAD

**Issue by AUsatenko** [puppetlabs/bolt#2272]
## Describe the Bug
when I execute
```Invoke-BoltCommand -Command  "Get-WMIObject Win32_Service -Filter ""Name like '%mon'"" | SELECT NAME,STARTNAME"  -Targets server```

Get an error: Unknown argument(s) like, %mon | SELECT NAME,STARTNAME'

## Expected Behavior
should return name and startname of the service on remote server

## Steps to Reproduce
1. Run powershell cmdlet in bug description

## Environment
 - Version 2.31
 - Platform Windows 10

**Comment by jpogran** [comment]
The reason this is occurring is that there are 3 levels of argument parsing happening: the parent PowerShell process invoking `Invoke-BoltCommand`, the bolt ruby argument parser, and the final PowerShell process on the target.

The `Invoke-BoltCommand` does some parsing to build a command line for the ruby bolt, which results in the following: 

```
❯ Invoke-BoltCommand -Command "Get-WMIObject Win32_Service -Filter ""Name like '%mon'""" -Targets localhost -Verbose
VERBOSE: Examining Command
VERBOSE: Parsing Command as default
VERBOSE: Examining Targets
VERBOSE: Parsing Targets as default
VERBOSE: Examining Verbose
VERBOSE: Parsing Verbose as switch parameter
VERBOSE: Executing C:\PROGRA~1\PUPPET~1\Bolt\bin\ruby -S -- C:\PROGRA~1\PUPPET~1\Bolt\bin\bolt command run 'Get-WMIObject Win32_Service -Filter "Name like '%mon'"' --targets 'localhost' --verbose
0 command
1 run
2 'Get-WMIObject Win32_Service -Filter Name
3 like
4 %mon'
5 --targets
6 localhost
7 --verbose
Unknown argument(s) like, %mon'
```

The problem is that the `command` to run now has single quotes around it, which invalidate the un-escaped single quotes inside, causing ruby ARGV to break apart the string into 2 more parts.

To compare:

```
❯ bolt command run "Get-WMIObject Win32_Service -Filter ""Name like '%rm'""" -t localhost
0 command
1 run
2 Get-WMIObject Win32_Service -Filter "Name like '%rm'"
3 -t
4 localhost
Started on localhost...
Finished on localhost:
  STDOUT:
    ExitCode  : 0
    Name      : WinRM
    ProcessId : 15724
    StartMode : Auto
    State     : Running
    Status    : OK
Successful on 1 target: localhost
Ran on 1 target in 0.94 sec
```

We could play around with different escaping strategies in PowerShell, but will run aground eventually with the conflicting escape characters (powershell is ` backtick` and ruby is `\`). Ultimately the cmdlet should not be introducing single quotes if the user did not want them, so we should fix that.

As a workaround while this is worked on, you can use the following `bolt` usage:

> Note I've changed the example service to look for to `rm`, because I didn't have any services locally that had `mon` in them

```
❯ bolt command run "Get-WMIObject Win32_Service -Filter ""Name like '%rm'""" -t localhost
Started on localhost...
Finished on localhost:
  STDOUT:
    ExitCode  : 0
    Name      : WinRM
    ProcessId : 15724
    StartMode : Auto
    State     : Running
    Status    : OK
Successful on 1 target: localhost
Ran on 1 target in 0.89 sec
```

**Comment by jpogran** [comment]
I also found #2299 while investigating this
