### ISSUE TITLE
Example incorrect

### ISSUE THREAD

**Issue by woter1832** [puppetlabs/bolt#2370]
## Describe the Change You Would Like
In your example, you say that `out::message` should return an object:
```
[
  {
    "target": "target0",
    "action": "task",
    "object": "package",
    "status": "success",
    "value": {
      "status": "uninstalled",
      "version": ""
    }
  }
]
```

When I try this from Puppet Enterprise, the console reports the error:
```
Plan output

{
  "msg" : "'out::message' parameter 'message' expects a String value, got ResultSet",
  "kind" : "bolt/plan-failure",
  "details" : {
    "class" : "Bolt::PAL::PALError"
  }
}
```
This suggests there are differences or changes that need to be highlighted in the documentation.

The section of documentation I refer to is: https://puppet.com/docs/bolt/latest/writing_plans.html#using-outmessage-to-debug-a-plan

> plan website::test(
>  TargetSpec $targets
> ) {
>   $check_mysql = run_task('package', $targets, "Check for MySQL", {'action' => 'status', 'name' => 'mysql'})
>   out::message($check_mysql)
> }

The specific line: `out::message($check_mysql)`
Thanks

**Comment by lucywyman** [comment]
Hello! That's probably because the version of PE you have is using an older version of Bolt from before we had added outputting objects instead of just strings. You can see [which version of Bolt is running in PE here](https://puppet.com/docs/pe/2019.8/component_versions_in_recent_pe_releases.html#puppet-enterprise-agent-and-server-components), and see the [documentation for debugging using out::message in PE here](https://puppet.com/docs/pe/2019.8/writing_plans_in_puppet_language_pe.html#outputting-to-the-cli-or-console) which indicates to pass `out::message` a string.

**Comment by woter1832** [comment]
@lucywyman ,
Thank you for your reply. You closed it before I had a chance to reply. I am pretty sure this is not the case. I am running the very latest version of PE (2019.8.4).

### Plan
```
plan base_windows::testplan (
  TargetSpec $targets,
  Optional[String] $contents = undef,
  String $filename,
){
  $targets.apply_prep

  $apply_results = apply($targets, '_catch_errors' => true) {
    class { 'base_windows::testpp':
      filename => $filename,
      contents => $contents,
    }
  }

  #return $apply_results

   $apply_results.each |$result| {
    $target = $result.target.name
    #notice( "testplan result: ${target}, ${result}")

    if $result.ok {
      notice("${target} returned a value: ${result.value}")
      out::message("${target} returned a value: ${result.value}")
    } else {
      notice( "${target} errored with a message: ${result.error.message}")
      out::message( "${target} errored with a message: ${result.error.message}")
    }
  }
}
```

### Error in PE console:
```
Plan output

{
  "msg" : "Evaluation Error: Unknown function: 'value'. (file: /opt/puppetlabs/server/data/orchestration-services/code/environments/development/modules/base_windows/plans/testplan.pp, line: 42, column: 51)",
  "kind" : "bolt/plan-failure",
  "details" : {
    "class" : "Bolt::PAL::PALError"
  }
}
```
(line 42 = `notice("${target} returned a value: ${result.value}")`)

Thanks

**Comment by beechtom** [comment]
@woter1832 The `apply` function returns `ApplyResult` objects, which have a different set of functions than `Result` objects. You can see the available functions here: https://puppet.com/docs/bolt/latest/bolt_types_reference.html#applyresult

**Comment by lucywyman** [comment]
Oh, I see, that's a very understandable mistake! That's because ApplyResult objects don't have a `value()` function - you might want `report()` or `to_data()` ([data type reference here](https://puppet.com/docs/bolt/latest/bolt_types_reference.html#applyresult)). We should definitely catch folks calling `value()` on that and either return the report or error and say you probably mean report. I'll reopen this for that work!
