### ISSUE TITLE
Unable to upgrade bolt via brew (OSX)

### ISSUE THREAD

**Issue by yakirgb** [puppetlabs/bolt#2435]
## Describe the Bug
Unable to upgrade bolt via brew (OSX), from 2.35.0 to 2.36.0
```
~$ brew upgrade puppet-bolt
==> Upgrading 1 outdated package:
puppetlabs/puppet/puppet-bolt 2.35.0 -> 2.36.0
==> Upgrading puppet-bolt
==> Caveats

    Puppet Bolt binaries are installed in /opt/puppetlabs/bolt/bin, which is sourced by an /etc/paths.d entry.
    /opt/puppetlabs/bolt/bin may not be included in your current $PATH but should be included in new shells.

==> Downloading https://downloads.puppet.com/mac/puppet-tools/10.15/x86_64/puppet-bolt-2.36.0-1.osx10.15.dmg
Already downloaded: /Users/yakir.g/Library/Caches/Homebrew/downloads/59d32d91e044a54c1a17ed3d88dc04ff7f08866bf598aba9e03aa95b8734c995--puppet-bolt-2.36.0-1.osx10.15.dmg
==> Purging files for version 2.36.0 of Cask puppet-bolt
Error: puppetlabs/puppet/puppet-bolt: SHA256 mismatch
Expected: 35267f348466e841085e95d27918197a82d5f8b4ddd7d247e6ca6c188823a127
  Actual: 14111da825fe29542e6a401982e388f920756be8dacab1fa5c8ed4498104a9d8
    File: /Users/yakir.g/Library/Caches/Homebrew/downloads/59d32d91e044a54c1a17ed3d88dc04ff7f08866bf598aba9e03aa95b8734c995--puppet-bolt-2.36.0-1.osx10.15.dmg
To retry an incomplete download, remove the file above.
```
## Expected Behavior
Upgrade should work

## Steps to Reproduce
```
brew upgrade puppet-bolt
```

## Environment
 - 2.35.0
 - OSX 10.15.7 Catalina
 - Homebrew 2.6.0

**Comment by lucywyman** [comment]
Hi thanks for raising this! This is an issue because we updated the Puppet package repos to use Puppet 7 packages instead of Puppet 6 packages, and Bolt doesn't yet publish packages to the Puppet 7 repos. All other repos (our apt repo, yum, etc.) pull from the `puppet-tools` repo, but homebrew was still pulling from the puppet repo.

All is a long way of saying: this has been fixed here: https://github.com/puppetlabs/homebrew-puppet/pull/246 and should successfully pull in Bolt 2.37.0 when it's released in a few hours here. I'll verify users can successfully upgrade once that's out, but I think this problem has already been fixed.

**Comment by lucywyman** [comment]
```
installer: Package name is puppet-bolt
installer: Installing at base path /
installer: The install was successful.
🍺  puppet-bolt was successfully installed!
osx@myhost ~ % bolt --version
2.37.0
```
Looks to be working now! Let us know if you have any issues.
