### ISSUE TITLE
Referencing files with Puppet file (puppet:///module/file) fails

### ISSUE THREAD

**Issue by lucywyman** [puppetlabs/bolt#2504]
## Describe the Bug
While some plan functions can specifically lookup files given their Puppet file path (such as `file::read()`), referencing `puppet:///mymodule/file` for files in a project in an apply block fails with:
```
Failed on localhost:
  Resources failed to apply for localhost
    File[/home/user/foo]: Could not retrieve information from environment production source(s) puppet:///bolt/myfile
```

## Expected Behavior
We should properly bundle module files when executing tasks so that module content, like files, are available from apply blocks.

## Steps to Reproduce
```
plan bolt (
  TargetSpec $targets
){
  apply($targets) {
    file { "/home/user/foo":
           source => "puppet:///modules/bolt/myfile"
    }
  }
}
```

```
bolt plan run bolt -t myhost
```

**Comment by nicklewis** [comment]
This may be the culprit:

https://github.com/puppetlabs/bolt/blob/main/lib/bolt/applicator.rb#L296

We override the modulepath to avoid syncing builtin content, but we therefore also lose the project directory.

**Comment by zbentley** [comment]
This is affecting me as well. The workaround is to modify any bolt-imported Puppet language modules so that their files are loaded via a `template` call, and move the files into from the `files` to the `templates` directory inside each module.

This is unfortunate, since third-party modules may also have issues, and because some of my files happen to have valid template interpolations in them, which breaks ERB/EPP.

**Comment by zbentley** [comment]
Confirmed working, thanks!!
