### ISSUE TITLE
Support non-github git repos

### ISSUE THREAD

**Issue by nmaludy** [puppetlabs/bolt#2522]
## Use Case
We are not allowed to host our code in external infrastructure, so all of our private code lives in on-prem git repos.

It would be great if `bolt module add` and `bolt module install` supported non-github git repos.

## Describe the Solution You Would Like
The ability to specify non-github git repos in the `modules` setting of `bolt-project.yaml`

**Comment by lucywyman** [comment]
## Solution for now
It may be a while before we can support all the module declarations people are interested in using (or modules that don't resolve). For now, a good workaround for this would be to add an option to individual modules to not resolve them with the `puppetfile-resolver`.

This should be an option for both Forge and Git module types that will omit the module from being part of the dependency resolution step when installing modules but will include the module in the final Puppetfile.
```
modules:
  - git: https://mygithmodule
    ref: main
    resolve: false
```
- What happens if a dependency has the same name as a module that doesn't resolve? Check existing behavior.
