### ISSUE TITLE
Receive "unable to get local issuer certificate" error when attempting to run bolt module add

### ISSUE THREAD

**Issue by AlanJinTS** [puppetlabs/bolt#2650]
## Describe the Bug
when i run “bolt module add puppetlabs-stdlib” for a init bolt project, i got the following error: "Unable to find module puppetlabs-stdlib on https://forgeapi.puppet.com: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)"

## Expected Behavior
i expected the module to get installed

## Steps to Reproduce
1. open powershell with runas
2. run "bolt module add puppetlabs-stdlib"

## Environment
 - windows 10
## Additional Context
I find a similar bug here [link](https://github.com/puppetlabs/bolt/issues/2171) and followed a workaround to set the "SSL_CERT_DIR" and "SSL_CERT_FILE" environment to "C:\Program Files\Puppet Labs\Bolt\ssl\certs" and "C:\Program Files\Puppet Labs\Bolt\ssl\cert.pem" respectively. but does not work either.

**Comment by andyfelton2** [comment]
Hi,

I've also hit this issue today. I've spent some time debugging it and I think the issue is down to the bolt.bat file which on my machine is setting BOLT_DIR=%BOLT_BASEDIR%\PUPPET which isn't correct.

I believe this should be without the PUPPET directory?

**Comment by jpogran** [comment]
Thank you @AlanJinTS for the report, apologies it is not working, this slipped by because of the forgiving nature of the gem loading parts of ruby.

I investigated and found the problem today, the fix which @andyfelton2 pointed out yesterday is correct. I have a PR up in our packaging repo and we will get this tested and deployed soon.
