### ISSUE TITLE
Noop for bolt

### ISSUE THREAD

**Issue by m0un10** [puppetlabs/bolt#2755]
## Use Case

I want to test my plan safely.

As bolt has `noop` for tasks, I was surprised to learn that `bolt plan` doesn't have this feature.

## Describe the Solution You Would Like

Running `bolt plan run <planName> --noop` runs with noop on all the tasks it calls so it doesn't actually make changes to the target environments. If the tasks don't support `noop` then the plan should fail with a message indicating that the plan doesn't support `noop` due tasks X,Y,Z etc.

## Describe Alternatives You've Considered

Ansible Playbooks with `check` mode.

## Additional Context

This is a bit of a showstopper for using bolt at the moment

**Comment by lucywyman** [comment]
## Solution
- This should only be supported as a flag, and cannot be set in the plan itself. No `--no-noop` flag, or `_noop` for the `run_plan` plan function.
- This should error if any functions other than `apply` or `run_task` are called, or if any tasks that are run don't support noop. Consider a noop executor that's swapped out for the regular executor when this flag is provided that errors if any functions besides run_task are called.
- We should ensure that the puppet_agent::install task supports noop so that `apply_prep` can be called safely.
- For both puppet and yaml plans, run until we hit a step that doesn't support noop and then error out.
- Investigate bug around `run_task_with` respecting executor noop setting.

**Comment by op-ct** [comment]
BoltSpec seems like the right tool for this.  I'm skeptical that a `bolt plan run --noop` could be reliable enough to be useful:

* Plans can include logic that makes decisions based on the results of `run_task` and `apply`.   
* If those functions run as `--noop`, they won't return the same ResultSets—which could cause the plan logic to behave differently than it would have with a real environment.  
* If `bolt plan run --noop` is restricted to only two plan functions, requires all tasks to support noop, and may even try to do different things, it's hard to see it being very useful as a noop.

On the other hand: 

* BoltSpec can mock `run_task`, `apply`, and [many other plan functions](https://puppet.com/docs/bolt/latest/boltspec_reference.html#mocks) to return expected ResultSets before test-running a plan and verifying that it does the right things—without ever touching a real environment.  
* Even better: BoltSpec can use different ResultSets to model various conditions and validate that a plan's behavior is correct under all of them.  
* IMO, this accomplishes the goal of running plans under noop better than an ambiguous `--noop` flag could.

**Comment by beechtom** [comment]
Closing this as we are unlikely to implement a noop mode for plans. For plans that run anything other than tasks that support running in noop mode, noop behavior is undefined. It's difficult to know what the proper action to run is for things like commands, scripts, and more. Additionally, as stated by @op-ct above, BoltSpec may be the correct tool for testing the behavior of a plan without touching a real environment.
