### ISSUE TITLE
Invoke-BoltScript Arguments Parameter Fails

### ISSUE THREAD

**Issue by glsc251** [puppetlabs/bolt#2788]
## Describe the Bug
PowerShell CMDLET Invoke-BoltScript does not pass Arguments parameter to bolt correctly. You have to enclose them in single quotes and the underlying code should split that apart and pass it to bolt. It does not matter what the script is doing with the PS command it passes it as a single string not three parameters.

## Expected Behavior
The following works correctly under Windows or Linux
```sh
bolt script run path/to/script.sh arg1 arg2 arg3 --targets 10.0.68.18 --user root --password-prompt
```
The script is copied to the target and the three parameters are passed to the script.

## Steps to Reproduce
```PowerShell
Invoke-BoltScript -Script C:\path\to\script.sh -Arguments 'arg1 arg2 arg3' -Targets 10.0.68.18 -User root -PasswordPrompt -Transport ssh
```

## Environment
 - Version [3.6.1]
 - Platform [Windows 10 and Debian 10]

**Comment by jpogran** [comment]
We'll first need to adjust the generator to make `-Arguments` have `ValueFromRemainingArguments` set to `$true`. This will tell the pwsh parser to take all non-bound args and pass them to `-Arguments`. 

The next step is to investigate https://github.com/puppetlabs/bolt/blob/main/pwsh_module/pwsh_bolt_internal.ps1#L32-L81 and determine if we need to add an array statement there so that the bolt commandline is generated correctly.
