### ISSUE TITLE
Support for per-target, timestamped or dynamic log filenames

### ISSUE THREAD

**Issue by breca** [puppetlabs/bolt#2898]
## Use Case
I'm using Bolt to provide self service capabilities to my users and I'd really like the ability to be able to get better visibility out of logging. Currently logging seems limited to a single files with configurable log levels which loses value rapidly when we are executing multiple concurrent jobs over dozens of nodes at a time.

## Describe the Solution You Would Like
I think there are multiple ways to improve this, such as a `per-target: true` logging option, `time-prefix: true` option, or simply being able to provide `logfile` and `loglevel` as optional parameters to a plan/task call, so that I could populate these using variables passed down from my self service solution (like usernames, job uuids, etc) - i.e `job-8761298-bolt.log`

## Describe Alternatives You've Considered
Log aggregation using external tools

**Comment by lucywyman** [comment]
Hmm, would exposing options to be able to use the Logging library's [rolling log files](https://github.com/TwP/logging/blob/ae9872d093833b2a5a34cbe1faa4e895a81f6845/lib/logging/appenders/rolling_file.rb) work for you? It's not exactly the same since it wouldn't distinguish each run, but could make the logfiles more comprehensible.

**Comment by breca** [comment]
Yeah, purely being able to do something like override the output log file would be handy
