### ISSUE TITLE
Provide a way to not leak bolt runner ruby environment to tasks run over local transport

### ISSUE THREAD

**Issue by donoghuc** [puppetlabs/bolt#2922]
## Use Case
When I run a ruby task over the local transport I dont want to necessarily run under the same context as the ruby env running bolt. 

## Describe the Solution You Would Like
When i disable [bundled-ruby](https://puppet.com/docs/bolt/latest/bolt_transports_reference.html#bundled-ruby) i do not want any ruby specific environment variables set when running the bolt process (maybe something like:
```
unset GEM_HOME
unset GEM_PATH
unset DLN_LIBRARY_PATH
unset RUBYLIB
unset RUBYLIB_PREFIX
unset RUBYOPT
unset RUBYPATH
unset RUBYSHELL
```
)

## Describe Alternatives You've Considered
Does this generalizes to being able to configure environment variables when running a task. For example maybe something like is done for interpreters:
```
interpreters:
  rb: /my/ruby
  env:
    GEM_HOME: /some/thing
```

## Additional Context
INnthe context of running a remote task over ace, we do not want to use the settings for GEM_PATH and GEM_HOME used to start the ace process. This is a specific issue within general weirdness executing ruby tasks over the local transport given the bolt runner will also be a ruby process. 

Also, somewhat related is https://github.com/puppetlabs/puppet/pull/8685 which is another approach at solving this particular issue in ACE>

**Comment by lucywyman** [comment]
Hmm, I'm having some trouble reproducing this in just Bolt. We [use Open3.popen3](https://ruby-doc.org/stdlib-2.7.2/libdoc/open3/rdoc/Open3.html#method-c-popen3) without any additional environment variables to open the subprocess, which should just preserve the existing user environment variables including GEM_HOME and GEM_PATH (even though we unset those in the [Bolt bin wrapper](
https://github.com/puppetlabs/bolt-vanagon/blob/main/resources/files/posix/bolt_env_wrapper) popen3 seems to reset to the user environment before adding those). The only place I can see at least GEM_PATH get set is [in the actual pe-plan-executor service definition](https://github.com/puppetlabs/bolt-vanagon/blob/main/resources/systemd/pe-plan-executor.service). Am I missing something?

**Comment by donoghuc** [comment]
The values of GEM_* we use to start the service that you linked to are the issue. We explicitly do not want those set when ruining the remote ruby tasks. 

It would be surprising to me if 
> which should just preserve the existing user environment variables including GEM_HOME and GEM_PATH
was the case? Are you saying that some hypothetical task `printenv` invoked over the local transport `SOME_ENV=preserved bolt task run printenv -t localhost` would have access to `SOME_ENV`? I dont think that is what we want. Instead, as you noted in our wrapper that starts the service environment variables used when the process that starts bolt are transferred to the ruby sub-process started by open3 which we want to 1. disable and/or 2. configure.

**Comment by lucywyman** [comment]
Yeah, that's what happens:
```
lucy ~/githubs/bolt (GH-2877) $ cat tasks/init.sh 
#!/bin/sh

printenv MY_ENV_VAR
lucy ~/githubs/bolt (GH-2877) $ echo $MY_ENV_VAR

lucy ~/githubs/bolt (GH-2877) $ MY_ENV_VAR='print me' bolt task run bolt -t localhost
Started on localhost...
Finished on localhost:
  print me
Successful on 1 target: localhost
Ran on 1 target in 0.09 sec
```

I guess since it seems like this is only an issue for Ace setting environment variables and then wanting to unset them, I'm wondering if you can override the variables in Ace when the vars are incorrect, rather than having to add a key to the task spec or some other feature? I just haven't heard of users wanting to do this for tasks, and in the past we've explicitly decided not to let users set env vars for tasks https://github.com/puppetlabs/bolt/issues/1899#issuecomment-645602209.

**Comment by donoghuc** [comment]
Ah, that env var behavior does make sense. I was contrasting in my head the difference between running over ssh and local on the same host. The ACE case is the first compelling use case for this I know if. I believe @nicklewis had thought of another one. 

We need `GEM_{HOME,PATH}` set for the ace (and bolt-server) services. I did bring up modifying the env vars through ruby once the service had started. My first thought was to do it in run_task requests, but that would be unsafe because multiple requests would be modifying the env vars at the same time which would be shared across all requests. 

I am curious what the other ways to do this already referenced 
> We should not do this for run_task, as tasks have a clear API and there are ways to do this already
 
from https://github.com/puppetlabs/bolt/issues/1899#issuecomment-645602209 are?

**Comment by nicklewis** [comment]
There are actually a few cases and they all have different behavior:
• bolt-server/ace
• bolt from a package
• bolt from bundler

bolt-server/ace _sets_ `GEM_PATH`[1], the `/opt/puppetlabs/bin/bolt` script in the package _unsets_ `GEM_PATH`, and `bundler exec bolt` from source sets `GEM_PATH` and stores the old value in `BUNDLER_ORIG_GEM_PATH`.

The _ideal_ (though difficult) behavior in all cases is that running the local transport (with `bundled-ruby: false`) should set `GEM_PATH` to whatever it was _before_ Bolt started running. That would make the behavior the same as what would happen if you just ran the task code directly, outside of Bolt.

Basically the problem is that if you're trying to run a Ruby script, the fact that the tool that runs it is written in Ruby happens to interfere and you get a muddled Ruby environment.

For example, I use rvm and therefore I can't use Bolt to run tasks that depend on ruby gems (like vmfloaty) on localhost. Bolt overrides `GEM_PATH` (by unsetting it) but leaves `PATH` alone, meaning my environment is inconsistent, such that rvm's Ruby is the first entry in `PATH`, but none of its environment variables are setup. The most correct behavior is for it to restore the original, unmodified environment when executing. The next most correct behavior is probably to _explicitly_ unset those environment variables (rather than the rubygem executable wrapper _happening_ to do it, meaning we don't get that same behavior is Bolt is executed another way).

[1] I'm using `GEM_PATH` as a stand-in for "all the ruby-related environment variables".

**Comment by nicklewis** [comment]
This is a bit different than setting env vars for a task, since in that case the task should set the variables it needs. This is more about configuring the target itself for _all_ Ruby tasks. In particular, setting `interpreters` to a binary is often _insufficient_ to actually configure the interpreter. You can point `.rb` at a particular Ruby binary, but a Ruby install is actually defined by a bunch of environment variables as well. So if stashing and restoring the original environment variables is too difficult (which I expect it is), a workaround would be allowing them to be explicitly specified for the interpreter.

**Comment by lucywyman** [comment]
Could we save the `GEM_PATH` (et al) to `BOLT_ORIG_GEM_PATH` as part of the wrapper script, then try to restore from that or `BUNDLER_ORIG_GEM_PATH` when executing locally with `bundled-ruby: false`?
