### ISSUE TITLE
Plans for integrating Bolt to work with elevated privilege management systems?

### ISSUE THREAD

**Issue by jdub55** [puppetlabs/bolt#731]
Are there any plans to get Bolt to work with elevated privilege access systems such as BoKs or PowerBroker? Or if there are inherent challenges / limitations with getting Bolt to work with these systems, can someone elaborate on what those are? (I know PCP is available as an alternate transport mechanism but this limits the amount of work I can do on servers that aren't yet being managed by Puppet)

**Comment by lucywyman** [comment]
We don't currently have plans to add support for elevated privilege systems. I don't know very much about PowerBroker or BoKs - what about Bolt makes it so those don't currently work?

**Comment by jdub55** [comment]
Thanks. I've been doing some more research after posting the question. I believe BoKs uses a PAM that ensures (at least for some implementations) 2-factor authentication is used which pretty much (by design) excludes tools like Bolt from working with it. I'm still trying to get some more info re: PowerBroker to see if it uses a similar model if there might be a way to plug into it somehow.

**Comment by wilrodriguez** [comment]
Powerbroker effectively functions similar like an audit friendly sudo. You can escalate for individual commands using the `pbrun` command. So the only functional difference between the two for most things, so far as I'm aware, is that you'd escalate with `pbrun` instead of sudo.

I'd really like to see bolt get this support so that we can avoid using ansible for these use-cases, since it already supports it out of the box currently.

**Comment by lucywyman** [comment]
Does `run_as_command` not work for this https://puppet.com/docs/bolt/1.x/bolt_configuration_options.html#ssh-transport-configuration-options?

**Comment by wilrodriguez** [comment]
Oh... yeah actually that should definitely work. I didn't realize that was there.

**Comment by MikaelSmith** [comment]
`run_as_command` has been finicky for some scenarios. Let us know if it doesn't work for `pbrun`.
