### ISSUE TITLE
Bolt for Windows uses incorrect interpreter path

### ISSUE THREAD

**Issue by alanraison** [puppetlabs/bolt#851]
Having installed bolt 1.10.0 on my Windows machine and added the `bin` folder to my path, I was unable to run bolt from my Git Bash shell. This was because all unix scripts had been set to an invalid interpreter:

```
C:/ProgramFiles64Folder/PuppetLabs/Bolt/bin/ruby.exe
```

Changing this (and all other script files in the directory) to:

```
C:\Progra~1\Puppet~1\Bolt\bin\ruby.exe
```

(corresponding with my bolt install path) fixed the issue. I was unable to use paths with spaces.

**Comment by MikaelSmith** [comment]
I don't think there are easy fixes for this. We can update our build process to use the paths you've noted so that the default install location is put in the script headers (those are generated during a ruby install). They wouldn't be right if you use a non-default install location.

I guess we could explore updating those files as part of the install process (somewhere in [WiX land](https://github.com/puppetlabs/bolt-vanagon/tree/master/resources/windows/wix)).

**Comment by lucywyman** [comment]
Closing as we don't (and would take a lot of effort) to support Git Bash.
