### ISSUE TITLE
Unable to locate SRPM or RPM spec file for puppet-bolt

### ISSUE THREAD

**Issue by pixdrift** [puppetlabs/bolt#927]
Hi,

I am trying to track down the SRPM or .spec file used to build the official Puppet Bolt RPM that is distributed on yum.puppet.com.

eg. Source RPM for this package
https://yum.puppet.com/puppet6/el/7/x86_64/puppet-bolt-1.14.0-1.el7.x86_64.rpm

Would it be possible to access a canonical source for this .spec/.srpm file? or include the .spec in this repository under a contrib directory?

**Comment by lucywyman** [comment]
Hi @pixdrift! We use an internal tool, Vanagon (https://github.com/puppetlabs/vanagon), to create our packages. You can see the configuration we use at https://github.com/puppetlabs/bolt-vanagon. It looks like that file is generated from a template as part of the Vanagon build. https://github.com/puppetlabs/vanagon/blob/master/lib/vanagon/platform/rpm.rb#L35 Hope that helps!

**Comment by pixdrift** [comment]
@lucywyman, thanks for the response 👍. Definitely helps.. and probably more than I expected.

Would it be possible to capture the .src.rpm file from this build process and include it in the artefacts uploaded to the Puppet repo? This would allow rapid changes to the RPM for end user/site specific customisations. Attempting to setup an equivalent Vanagon build environment when making some some minor changes to an RPMs contents is probably a little overkill 😱 

There does seem to be a precedent for including .src RPMs, but not sure on the significance (ie. how/why this set of packages was selected for .src.rpm distribution, but other packages weren't)
https://yum.puppet.com/el/7Server/PC1/SRPMS/

Thanks again.

**Comment by underscorgan** [comment]
Hi @pixdrift,

Unfortunately, with the way vanagon builds projects right now there is no way to generate meaningful source RPMs. The way the builds happen, all code compilation happens using a Makefile that is executed prior to packaging rather than in a `%build` step in the spec file. So, by the time we get to generating a spec file and building packages all the sources have already been patched and compiled.

We do have a ticket to try to make this easier for vanagon (https://tickets.puppetlabs.com/browse/VANAGON-71), but I don't have an eta for that work. It will probably not be a particularly easy task and it is not prioritized.

The packages with SRPMs were packaged using [ezbake](https://github.com/puppetlabs/ezbake) (our tool for packaging the server-side clojure projects). Ezbake no longer supports source RPMs due to changes in how the packages are built, those SRPMs are from before those changes.

**Comment by pixdrift** [comment]
Thanks for the response @underscorgan, understand the situation. Vanagon sounds similar to Chef Omnibus https://github.com/chef/omnibus

Would it still be possible to get a copy of the resultant spec or .src.rpm (understand it's not technically source)? It will just save me from pulling apart/re-creating the binary RPM for customisation. 😃

**Comment by underscorgan** [comment]
Hi @pixdrift , I can try to get the spec up somewhere for you. We don't really want to publish these to the normal repos since they aren't really src rpms, but I'll try to get a gist. If you let me know your OS/puppet-bolt version I can make sure to generate the correct thing.

I'm also looking into trying to get some docker images with a vanagon build environment on them to make it easier for external folks to build things. Let me know if that's something that would be helpful for you, I'm planning on working on that some tomorrow so could have something up fairly soon there.

**Comment by pixdrift** [comment]
@underscorgan, yeah I think a build container would be helpful. I built a similar container to build the `buildah` rpm, you provide the git commit ID and it spits out an RPM.

It is on gitlab here:
https://gitlab.com/pixdrift/buildah-scripts/blob/master/el7.buildah.rpmbuild.sh

Makes it easy to slot into a build pipeline then. Would be good to get a generic vanagon container that you can provide a git repo / commit to that produces an RPM. 👍 

Thanks for following up.

**Comment by underscorgan** [comment]
Hi @pixdrift ! This took a little longer than expected but I wanted to make sure to get something that would work relatively well. I pushed an image up to dockerhub [here](https://cloud.docker.com/repository/docker/underscorgan/vanagon), and built from [this repo](https://github.com/underscorgan/vanagon-docker-builds).

I put a bunch of information specifically on building puppet-bolt and bolt-runtime in the README. Let me know if anything seems weird or isn't working for you.

As a caveat, this image is not officially supported, but I will make an effort to keep this updated and functional.

**Comment by pixdrift** [comment]
@underscorgan, had a quick skim of everything and looks great 👍 will get some time over the weekend to recreate it on my side and let you know how it goes. Thanks for the Dockerfile, definitely solves the gaps in build process.

**Comment by lucywyman** [comment]
I'm going to close this since it seems resolved, let me know if we need to reopen
